 spring:
   server: 8085
   datasource:
     url: jdbc:mysql://localhost:3306/jwt_security_1
     username: root
     password: Experience@2805
     driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
     hibernate:
       ddl-auto: create-drop
     show-sql: true
     properties:
       hibernate:
         format_sql: true
     database: MYSQL
     database-platform: org.hibernate.dialect.MySQL8Dialect




